Download firmware matching manifest and incorporate into builds (#468)
* Checkpoint

* Cleanup

* Fix workflows (#453)

* replace deprecated set-output commands in github actions

* fix workflow

* Cache Ubuntu pip cache and results of setup-environment.sh (#462)

* replace deprecated set-output commands in github actions

* fix workflow

* Checkpoint

* Cleanup

* cache results of setup-environment.sh

* fix typo

---------

Co-authored-by: Carson Holgate <carsonholgate@gmail.com>

* Fix Windows build (#463)

* replace deprecated set-output commands in github actions

* fix workflow

* Checkpoint

* Cleanup

* Checkpoint

* Cleanup

* Fix workflows (#453)

* replace deprecated set-output commands in github actions

* fix workflow

* cache results of setup-environment.sh

* fix typo

* Cache Ubuntu pip cache and results of setup-environment.sh (#462)

* replace deprecated set-output commands in github actions

* fix workflow

* Checkpoint

* Cleanup

* cache results of setup-environment.sh

* fix typo

---------

Co-authored-by: Carson Holgate <carsonholgate@gmail.com>

* fix windows build

* cache files for Windows build

---------

Co-authored-by: Carson Holgate <carsonholgate@gmail.com>

* change build workflow to download firmware version matching manifest, cache, and incorporate into desktop builds

* Allow upload for both v* and test* releases

* Update manifest.txt

Use existing release name

---------

Co-authored-by: Carson Holgate <carsonholgate@gmail.com>
Co-authored-by: dl1com <1631996+dl1com@users.noreply.github.com>

diff --git a/.github/workflows/build-multi-os.yml b/.github/workflows/build-multi-os.yml
--- a/.github/workflows/build-multi-os.yml
+++ b/.github/workflows/build-multi-os.yml
@@ -37,6 +37,129 @@ jobs:
         echo "sha-short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
         echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
         echo "draft=$(git describe --tags | sed -e 's/^test.*/true/;s/^v.*/false/')" >> $GITHUB_OUTPUT
+    - name: Get firmware version matching manifest
+      run: |
+        manifest=$(cat src/main/resources/base/ayab/firmware/manifest.txt)"
+        available=$(curl -s https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases | grep -e 'releases/tag/v' -e 'releases/tag/test' | sed 's/.*releases\/tag\///;s/\".*//')"
+        match=$(for x in $available; do echo $x; done | grep ^$manifest | sort -r | head -1)
+        if [[ $match ]]
+        then
+          cd /src/main/resources/base/ayab/firmware/
+          wget https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/download/v$match/*.hex
+        else
+          echo "Error: could not find firmware release matching manifest"
+          exit 1
+        fi
+    - name: Cache firmware
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+    - name: Set PACKAGE_VERSION
+      run: |
+        echo ${{steps.vars.outputs.tag}} > src/main/resources/base/ayab/package_version
+        sed -i 's/PACKAGE_VERSION/${{steps.vars.outputs.tag}}/' src/build/settings/base.json
+        cat src/main/resources/base/ayab/package_version
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v4
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Install dependencies
+      run: |
+        sudo apt-get install -y avrdude libasound2-dev
+    - name: Restore pip cache
+      id:   pip-cache
+      uses: actions/cache@v3
+      with:
+        path: ~/.cache/pip
+        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+    - name: Install Python modules
+      run: |
+        python -m pip install --upgrade pip
+        python -m pip install --upgrade setuptools
+        python -m pip install -r requirements.txt
+    - name: Cache Python modules
+      if:   steps.pip-cache.outputs.cache-hit != 'true'
+      uses: actions/cache/save@v3
+      with:
+        path: ~/.cache/pip
+        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+    - name: Use cached gui files (1)
+      id:   gui1-cache
+      uses: actions/cache@v3
+      with:
+        path: src/main/python/ayab/*_gui.py
+        key:  gui1-${{ hashFiles('src/main/python/ayab/*_gui.ui') }}
+    - name: Use cached gui files (2)
+      id:   gui2-cache
+      uses: actions/cache@v3
+      with:
+        path: src/main/python/ayab/engine/*_gui.py
+        key:  gui2-${{ hashFiles('src/main/python/ayab/engine/*_gui.ui') }}
+    - name: Use cached logo
+      id:   logo-cache
+      uses: actions/cache@v3
+      with:
+        path: src/main/python/ayab/ayab_logo_rc.py
+        key:  logo-${{ hashFiles('src/main/python/ayab/ayab_logo_rc.qrc') }}
+    - name: Use cached translation files
+      id:   qm-cache
+      uses: actions/cache@v3
+      with:
+        path: src/main/resources/base/ayab/translations/*.qm
+        key:  qm-${{ hashFiles('src/main/resources/base/ayab/translations/ayab-translation-master.tsv') }}
+    - name: Convert UI and translation files
+      if:   ${{ (steps.gui1-cache.outputs.cache-hit != 'true') ||
+                (steps.gui2-cache.outputs.cache-hit != 'true') ||
+                (steps.logo-cache.outputs.cache-hit != 'true') ||
+                (steps.qm-cache.outputs.cache-hit   != 'true') }}
+      run: |
+        sudo apt install -y qt5-default qttools5-dev-tools
+        ./setup-environment.sh
+    - name: Cache gui files (1)
+      if:   ${{ (steps.gui1-cache.outputs.cache-hit != 'true') }}
+      uses: actions/cache/save@v3
+      with:
+        path: src/main/python/ayab/*_gui.py
+        key:  gui1-${{ hashFiles('src/main/python/ayab/*_gui.ui') }}
+    - name: Cache gui files (2)
+      if:   ${{ (steps.gui2-cache.outputs.cache-hit != 'true') }}
+      uses: actions/cache/save@v3
+      with:
+        path: src/main/python/ayab/*_gui.py
+        key:  gui2-${{ hashFiles('src/main/python/ayab/engine/*_gui.ui') }}
+    - name: Cache logo
+      if:   ${{ (steps.logo-cache.outputs.cache-hit != 'true') }}
+      uses: actions/cache/save@v3
+      with:
+        path: src/main/python/ayab/ayab_logo_rc.py
+        key:  logo-${{ hashFiles('src/main/python/ayab/ayab_logo_rc.qrc') }}
+    - name: Cache translation files
+      if:   ${{ (steps.qm-cache.outputs.cache-hit != 'true') }}
+      uses: actions/cache/save@v3
+      with:
+        path: src/main/resources/base/ayab/translations/*.qm
+        key:  qm-${{ hashFiles('src/main/resources/base/ayab/translations/ayab-translation-master.tsv') }}
+
+  build-deb:
+    name: Create and upload Ubuntu release
+    needs: setup
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        python-version: [3.6]
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        submodules: recursive
+    - name: Set variables
+      id: vars
+      shell: bash
+      run: |
+        echo "sha-short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+        echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
+        echo "draft=$(git describe --tags | sed -e 's/^test.*/true/;s/^v.*/false/')" >> $GITHUB_OUTPUT
     - name: Set PACKAGE_VERSION
       run: |
         echo ${{steps.vars.outputs.tag}} > src/main/resources/base/ayab/package_version
@@ -177,6 +300,13 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools
         python -m pip install -r requirements.txt
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
@@ -280,6 +410,13 @@ jobs:
         python -m pip install --upgrade setuptools
         python -m pip install -r requirements.txt
         python -m pip install -r windows-build\windows_build_requirements.txt
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
@@ -388,6 +525,13 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools
         python -m pip install -r requirements.txt
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
@@ -504,6 +648,13 @@ jobs:
       run: |
         echo "usr/bin" >> $GITHUB_PATH
         echo "opt/${{steps.vars.outputs.python}}/bin" >> $GITHUB_PATH
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
