change build workflow to download firmware version matching manifest, cache, and incorporate into desktop builds

diff --git a/.github/workflows/build-multi-os.yml b/.github/workflows/build-multi-os.yml
--- a/.github/workflows/build-multi-os.yml
+++ b/.github/workflows/build-multi-os.yml
@@ -37,6 +37,24 @@ jobs:
         echo "sha-short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
         echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
         echo "draft=$(git describe --tags | sed -e 's/^test.*/true/;s/^v.*/false/')" >> $GITHUB_OUTPUT
+    - name: Get firmware version matching manifest
+      run: |
+        manifest=$(cat src/main/resources/base/ayab/firmware/manifest.txt)"
+        available=$(curl -s https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases | grep 'releases/tag/v' | sed 's/.*releases\/tag\/v//;s/\".*//')"
+        match=$(for x in $available; do echo $x; done | grep ^$manifest | sort -r | head -1)
+        if [[ $match ]]
+        then
+          cd /src/main/resources/base/ayab/firmware/
+          wget https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/download/v$match/*.hex
+        else
+          echo "Error: could not find firmware release matching manifest"
+          exit 1
+        fi
+    - name: Cache firmware
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
     - name: Set PACKAGE_VERSION
       run: |
         echo ${{steps.vars.outputs.tag}} > src/main/resources/base/ayab/package_version
@@ -177,6 +195,13 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools
         python -m pip install -r requirements.txt
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
@@ -280,6 +305,13 @@ jobs:
         python -m pip install --upgrade setuptools
         python -m pip install -r requirements.txt
         python -m pip install -r windows-build\windows_build_requirements.txt
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
@@ -388,6 +420,13 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools
         python -m pip install -r requirements.txt
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
@@ -504,6 +543,13 @@ jobs:
       run: |
         echo "usr/bin" >> $GITHUB_PATH
         echo "opt/${{steps.vars.outputs.python}}/bin" >> $GITHUB_PATH
+    - name: Restore cached firmware
+      id:   firmware-cache
+      uses: actions/cache/save@v3
+      with:
+        path: /src/main/resources/base/ayab/firmware/*.hex
+        key: firmware-${{ hashFiles('/src/main/resources/base/ayab/firmware/*.hex') }}
+        fail-on-cache-miss: true
     - name: Restore cached gui files (1)
       id:   gui1-cache
       uses: actions/cache@v3
